/// Versioned, customer-specific policy text. Never fall back to shared restaurant
/// settings here. Updating these documents does not change any backend behavior.
class GoLegalSection {
  const GoLegalSection({required this.id, required this.titleAr, required this.titleEn,
    required this.bodyAr, required this.bodyEn});
  final String id;
  final String titleAr;
  final String titleEn;
  final String bodyAr;
  final String bodyEn;
  String title(bool ar) => ar ? titleAr : titleEn;
  String body(bool ar) => ar ? bodyAr : bodyEn;
}

class GoLegalDocument {
  const GoLegalDocument({required this.id, required this.titleAr, required this.titleEn,
    required this.summaryAr, required this.summaryEn, required this.sections});
  final String id;
  final String titleAr;
  final String titleEn;
  final String summaryAr;
  final String summaryEn;
  final List<GoLegalSection> sections;
  String title(bool ar) => ar ? titleAr : titleEn;
  String summary(bool ar) => ar ? summaryAr : summaryEn;
}

abstract final class GoCustomerLegal {
  static const revision = 'go-customer-legal-2026-09-26';
  static const updatedAt = '2026-09-26';

  static const terms = GoLegalDocument(
    id: 'terms', titleAr: 'الشروط والأحكام', titleEn: 'Terms and conditions',
    summaryAr: 'تنظّم هذه الشروط استخدام Go Customer لطلب مناديب التوصيل والخدمات المهنية والمنزلية، والتعامل مع عروض الأسعار والدفع والمحفظة والدعم.',
    summaryEn: 'These terms govern Go Customer for requesting couriers, professional and home services, and using quotations, payments, the wallet and support.',
    sections: [
      GoLegalSection(id: 'platform', titleAr: '1. التطبيق والأطراف', titleEn: '1. The app and the parties',
        bodyAr: 'Go Customer، ويشار إليه باسم «GO» أو «المنصة»، يتيح للعميل البحث عن الخدمات وإرسال الطلبات والتواصل مع مناديب التوصيل ومقدمي الخدمات عبر منظومة GO. تشمل الخدمات المهن والصيانة والنظافة وغيرها من الفئات المعروضة فعليًا في التطبيق.\n\nيقصد بالعميل طالب الخدمة، وبالشريك المندوب أو مقدم الخدمة الذي يتلقى الطلب. توفّر إدارة GO الوسيلة التقنية لتنظيم الطلب والتواصل والدفع حيثما يكون متاحًا، وينفّذ الشريك الخدمة المتفق عليها. لا يلغي هذا التوزيع مسؤولية أي طرف عن أفعاله أو التزاماته القانونية.',
        bodyEn: 'Go Customer, referred to as GO or the platform, allows customers to find services, send requests and communicate with couriers and service providers through the GO system. Services include trades, repairs, cleaning and other categories actually displayed in the app.\n\nThe customer requests the service; the partner is the courier or provider receiving the request. GO management provides the technical means to organise requests, communication and payments where available, while the partner performs the agreed service. This allocation does not remove any party’s responsibility for its actions or legal obligations.'),
      GoLegalSection(id: 'account', titleAr: '2. الأهلية والحساب والدخول كزائر', titleEn: '2. Eligibility, accounts and guests',
        bodyAr: 'يلزم توافر الأهلية القانونية اللازمة للتعاقد، وتقديم بيانات صحيحة ومحدّثة، واستخدام رقم هاتف وبريد إلكتروني يحق لك استخدامهما. لا يجوز انتحال هوية الغير أو إنشاء حساب مستقل لقاصر لا يملك أهلية التعاقد. عند الحجز نيابة عن شخص آخر، يجب أن تكون مخولًا بذلك وأن تخبره باستخدام بياناته لتنفيذ الطلب.\n\nيمكن للزائر تصفح الخدمات المتاحة، بينما تتطلب بعض الوظائف تسجيل الدخول واستكمال البيانات. احتفظ بكلمة المرور ورموز التحقق سرية، وأبلغ الدعم عند الاشتباه في استخدام حسابك دون إذن. التحقق من البريد الإلكتروني لا يعني وحده التحقق من ملكية رقم الهاتف.',
        bodyEn: 'You must have the legal capacity required to contract, provide accurate and current details, and be entitled to use the phone number and email address supplied. Do not impersonate others or create an independent account for a minor who lacks contractual capacity. When booking for someone else, you must be authorised and tell them how their details will be used for the request.\n\nGuests may browse available services; some functions require sign-in and profile completion. Keep passwords and verification codes private and contact support about suspected unauthorised access. Email verification alone does not verify ownership of a phone number.'),
      GoLegalSection(id: 'requests', titleAr: '3. إرسال الطلب ونطاق الخدمة', titleEn: '3. Requests and service scope',
        bodyAr: 'راجع نوع الخدمة ووصف العمل والموقع وبيانات التواصل قبل إرسال الطلب، واذكر أي مخاطر أو احتياجات مؤثرة. إرسال الطلب ليس ضمانًا لقبوله أو لتوافر شريك؛ يتوقف ذلك على التغطية والتخصص ونطاق عمل الشركاء.\n\nفي التوصيل، حدّد عنواني الاستلام والتسليم وبيانات المستلم ومحتويات الشحنة بدقة، مع تغليف مناسب. لا تستخدم التطبيق لطلبات أو شحنات غير قانونية أو خطرة أو مواد محظورة. اتفق على احتياجات التعامل الخاص قبل التنفيذ، ولا تعتبر الصور الدعائية وصفًا ملزمًا لنطاق كل خدمة.',
        bodyEn: 'Check the service, work description, location and contact details before submitting a request, and disclose relevant risks or requirements. Sending a request does not guarantee acceptance or partner availability; coverage, specialism and partner service areas apply.\n\nFor delivery, accurately provide pickup and drop-off addresses, recipient details and shipment contents, with suitable packaging. Do not request illegal or dangerous work or prohibited shipments. Agree on special handling requirements before performance. Promotional images do not define the scope of every service.'),
      GoLegalSection(id: 'quotes', titleAr: '4. عروض الأسعار والعمولة', titleEn: '4. Quotations and commission',
        bodyAr: 'عندما يعتمد الطلب على عرض سعر، لا يصبح العرض اتفاقًا نهائيًا إلا بعد موافقة العميل والشريك عليه. السعر المتفق عليه هو السعر النهائي للنطاق الموضح في العرض، ولا تضاف إليه عمولة المنصة مرة أخرى على العميل. يجب توضيح أي ضريبة أو تكلفة تدخل ضمن إجمالي العرض قبل الموافقة.\n\nلا تستحق عمولة لمجرد إرسال الطلب أو تقديم عرض أو رفضه؛ يرتبط احتسابها بقبول الطرفين للعرض. أي مبلغ إرشادي أو تقديري قبل الاتفاق ليس تفويضًا بتحصيل سعر نهائي لم توافق عليه.',
        bodyEn: 'Where a request uses a quotation, it becomes a final agreement only after both the customer and partner accept it. The agreed amount is the final price for the scope specified in the offer; platform commission must not be added again to the customer’s price. Any tax or cost forming part of the total must be explained before acceptance.\n\nCommission is not due merely for sending a request, submitting an offer or rejecting it; its calculation is tied to both parties accepting the offer. An indicative estimate before agreement is not permission to collect an unapproved final price.'),
      GoLegalSection(id: 'changes', titleAr: '5. تغيير السعر والأعمال الإضافية', titleEn: '5. Price changes and additional work',
        bodyAr: 'أي تعديل للسعر أو نطاق العمل أو تكلفة الخامات وقطع الغيار يحتاج إلى توضيح وموافقة صريحة جديدة قبل تنفيذه أو تحصيله. لا يجوز تغيير السعر المتفق عليه من طرف واحد. عند رفض عرض معدل، لا يعتبر الرفض موافقة على السعر الجديد.\n\nاحتفظ بتفاصيل الاتفاق داخل التطبيق أو في سجل مكتوب يمكن تقديمه للدعم. لا يجوز تحصيل المبلغ نفسه أو عمولة العملية نفسها مرتين، وأي تعديل مالي يراعى فيه ما سبق دفعه.',
        bodyEn: 'Changes to the price, work scope, materials or spare-part costs require explanation and fresh explicit agreement before performance or collection. An agreed price must not be changed unilaterally. Rejecting a revised offer is not acceptance of its new price.\n\nKeep the agreement in the app or in a written record that can be supplied to support. The same amount or transaction commission must not be collected twice, and adjustments must account for amounts already paid.'),
      GoLegalSection(id: 'payments', titleAr: '6. وسائل الدفع', titleEn: '6. Payment methods',
        bodyAr: 'استخدم فقط وسيلة الدفع المتاحة والمفعلة لطلبك داخل التطبيق، مثل النقد أو رصيد التطبيق أو البطاقة البنكية أو المحفظة الإلكترونية بحسب ما يظهر لك. لا يعني ذكر وسيلة في هذه الشروط أنها مفعلة على جميع الأجهزة أو الطلبات.\n\nقد تتطلب المدفوعات الإلكترونية تحققًا من البنك أو مقدم الدفع. لا تشارك الرقم السري أو رمز تأكيد الدفع مع الشريك أو الدعم. احتفظ بإثبات الدفع، ولا تعاود الدفع عند تعطل الصفحة قبل مراجعة حالة العملية، تجنبًا للدفع المكرر.',
        bodyEn: 'Use only a payment method available and enabled for your request, such as cash, app balance, a bank card or an electronic wallet as displayed. Mentioning a method here does not mean it is enabled for every device or request.\n\nElectronic payments may require bank or payment-provider verification. Do not share payment PINs or verification codes with partners or support. Keep payment evidence and check transaction status before paying again after a page error, to avoid duplicate payment.'),
      GoLegalSection(id: 'wallet', titleAr: '7. رصيد المحفظة والتحويلات', titleEn: '7. Wallet balance and transfers',
        bodyAr: 'تعرض المحفظة الرصيد وسجل العمليات الذي يرسله النظام. الشحن واستخدام الرصيد والتحويل متاح فقط وفق الوظائف والقيود المعروضة وقت العملية؛ لا تعد هذه الشروط بإمكانية سحب نقدي أو تحويل خارجي غير متاح داخل التطبيق.\n\nراجع المبلغ وبيانات المستفيد قبل تأكيد التحويل، وأبلغ الدعم فورًا عن خصم غير معروف أو رصيد غير صحيح. حذف التطبيق أو الحساب لا يعد تنازلًا عن رصيد أو استرداد مستحق؛ راجع الدعم لتسوية الرصيد والطلبات المرتبطة بالحساب.',
        bodyEn: 'The wallet displays the balance and transaction history supplied by the system. Top-up, balance use and transfers are available only within the functions and restrictions shown at the time. These terms do not promise cash withdrawal or external transfers that are not available in the app.\n\nCheck the amount and recipient before confirming a transfer, and promptly report unknown deductions or an incorrect balance. Removing the app or deleting an account does not waive a balance or refund owed; contact support to settle balances and linked requests.'),
      GoLegalSection(id: 'timing', titleAr: '8. التنفيذ والمواعيد والسلامة', titleEn: '8. Performance, timing and safety',
        bodyAr: 'يعتمد وقت الوصول والتنفيذ على اتفاقك مع الشريك وطبيعة الخدمة والطريق والموقع. الأوقات التقديرية لا تعني ضمان الوصول في دقيقة محددة، مع بقاء الالتزام بإبلاغك بالتأخير المؤثر والتعامل معه.\n\nوفّر وصولًا آمنًا للموقع، وتحقق من هوية الشريك وتطابقه مع بيانات الطلب. لا تطلب عملًا يحتاج إلى ترخيص أو تأهيل متخصص من شخص غير مؤهل. GO ليس بديلًا لخدمات الطوارئ؛ عند وجود خطر فوري اتصل بالجهة المختصة.',
        bodyEn: 'Arrival and completion depend on your agreement with the partner, the work, route and location. Estimates are not a guarantee of arrival at an exact minute; material delays should still be communicated and addressed.\n\nProvide safe access and check that the arriving partner matches the request details. Do not ask an unqualified person to perform work requiring specialist qualifications or authorisation. GO is not an emergency service; contact the appropriate authority for immediate danger.'),
      GoLegalSection(id: 'cancellation', titleAr: '9. الإلغاء وعدم إتمام الخدمة', titleEn: '9. Cancellation and non-performance',
        bodyAr: 'يمكن طلب الإلغاء من الخيارات المتاحة للطلب أو عبر الدعم. قبل الاتفاق لا تنشأ عمولة لمجرد الطلب أو رفض العرض. بعد الاتفاق، تعتمد معالجة الإلغاء على حالة الطلب وما تم تنفيذه فعليًا وسبب الإلغاء.\n\nأي رسوم إلغاء أو مقابل انتقال أو معاينة يجب أن تكون موضحة ومقبولة مسبقًا؛ لا تسمح هذه الشروط بفرض رسوم مبهمة أو خصم كامل قيمة خدمة لم تنفذ. إذا ألغى الشريك أو تعذر التنفيذ، تواصل مع الدعم لتحديد استكمال الطلب أو إلغائه وتسوية أي مبلغ مستحق وفق القانون.',
        bodyEn: 'Request cancellation through the options available for the order or through support. Before agreement, merely requesting a service or rejecting an offer does not create commission. After agreement, cancellation handling depends on order status, work actually performed and the reason.\n\nAny cancellation, travel or inspection charge must have been disclosed and agreed beforehand. These terms do not authorise unspecified fees or charging the full value of an unperformed service. If the partner cancels or cannot perform, contact support to arrange continuation or cancellation and settle amounts due under applicable law.'),
      GoLegalSection(id: 'refunds', titleAr: '10. الاسترداد والاعتراض على المدفوعات', titleEn: '10. Refunds and payment disputes',
        bodyAr: 'يمكن طلب مراجعة مبلغ مكرر أو مدفوع لخدمة لم تتم أو خدمة محل شكوى، مع رقم الطلب وإثبات الدفع والتفاصيل المتاحة. يتحدد الاسترداد الكامل أو الجزئي بحسب الواقعة وما نفذ والحقوق المقررة قانونًا، وليس بقرار تعسفي يسقط حق العميل.\n\nالأصل رد المبلغ المستحق إلى وسيلة الدفع الأصلية حيثما تسمح بذلك الوسيلة، ولا يستبدل برد إلى رصيد التطبيق دون موافقتك متى كان لك حق في استرداد نقدي. يتأثر وقت ظهور المبلغ بإجراءات البنك أو مقدم الدفع؛ لا نحدد هنا مدة غير متحقق منها، ولا يخل ذلك بالمواعيد القانونية الملزمة.',
        bodyEn: 'You may ask for review of a duplicate charge, payment for an unperformed service or a disputed service, providing the request number, payment evidence and relevant details. Full or partial reimbursement depends on the facts, work performed and legal rights, not an arbitrary decision removing customer rights.\n\nAmounts owed should normally return to the original payment method where supported, rather than being replaced with app credit without your agreement when you are entitled to a monetary refund. Posting time depends on the bank or payment provider; no unverified period is promised here, and mandatory legal deadlines still apply.'),
      GoLegalSection(id: 'conduct', titleAr: '11. الاستخدام المقبول والمحتوى', titleEn: '11. Acceptable use and content',
        bodyAr: 'يمنع الاحتيال والطلبات الوهمية والتحرش والتهديد والإساءة والتلاعب بالعروض أو المدفوعات أو محاولة الوصول إلى حسابات الغير. لا ترفع صورًا أو بيانات تخص آخرين دون مسوغ، ولا ترسل معلومات غير لازمة للخدمة أو بيانات دفع سرية في الدردشة.\n\nتظل حقوقك في المحتوى الذي تقدمه محفوظة، وتسمح باستخدامه بالقدر اللازم لتشغيل الطلب وتقديم الدعم وتسوية النزاع، وليس تصريحًا مفتوحًا باستخدام صورك في الدعاية. لا يجوز نسخ علامة GO أو محتوى التطبيق بما يعتدي على حقوق أصحابه.',
        bodyEn: 'Fraud, fake requests, harassment, threats, abuse, manipulating offers or payments, and unauthorised account access are prohibited. Do not upload other people’s images or data without a lawful reason, or send unnecessary information or payment secrets in chat.\n\nYou retain rights in the content you submit and permit its use as needed to operate the request, provide support and resolve disputes. This is not unrestricted permission to use your images in advertising. Do not copy GO branding or app content in ways that infringe its owners’ rights.'),
      GoLegalSection(id: 'responsibility', titleAr: '12. جودة الخدمة والمسؤولية', titleEn: '12. Service quality and responsibility',
        bodyAr: 'يلتزم الشريك بنطاق العمل والسعر والمواصفات المتفق عليها وبالمتطلبات المهنية والقانونية ذات الصلة. ظهور الشريك على المنصة أو وجود تقييم لا يشكل وحده ضمانًا مطلقًا للجودة أو دليلًا على ترخيص مهني بعينه.\n\nراجع التنفيذ وأبلغ عن العيب أو الضرر مع ما يتاح من أدلة. تساعد GO في تلقي الشكوى ومراجعة سجل الطلب والتواصل مع الأطراف. لا تستبعد هذه الشروط مسؤولية GO أو الشريك التي لا يجوز استبعادها قانونًا، ولا تسقط حقوق الإصلاح أو إعادة الأداء أو التعويض أو الاسترداد حيث تستحق.',
        bodyEn: 'Partners must follow the agreed scope, price and specifications and relevant professional and legal requirements. A listing or rating alone is not an absolute quality guarantee or proof of a particular professional licence.\n\nReview the work and report defects or damage with available evidence. GO helps receive complaints, review request records and contact the parties. These terms do not exclude GO’s or the partner’s non-excludable liability or remove rights to repair, repeat performance, compensation or reimbursement where due.'),
      GoLegalSection(id: 'support', titleAr: '13. الدعم والشكاوى والقانون المطبق', titleEn: '13. Support, complaints and applicable law',
        bodyAr: 'للاستفسارات أو الشكاوى، استخدم «المساعدة والدعم» داخل Go Customer واذكر رقم الطلب أو العملية دون إرسال كلمات مرور أو رموز تحقق. يمكن تقييد استخدام مخالف لحماية المستخدمين أو التحقق من واقعة، مع إتاحة التواصل مع الدعم وعدم إهدار الرصيد أو الحقوق المستحقة.\n\nتطبق القوانين المصرية ذات الصلة، بما فيها القواعد الإلزامية لحماية المستهلك والبيانات. لا يمنع التواصل مع الدعم حقك في اللجوء إلى جهاز حماية المستهلك أو الجهة الرقابية المختصة أو القضاء، ولا تفرض هذه الشروط تنازلًا عن تلك الحقوق.',
        bodyEn: 'For questions or complaints, use Help and support inside Go Customer and include the request or transaction number without passwords or verification codes. Misuse may be restricted to protect users or investigate an incident, while retaining access to support and respecting balances and accrued rights.\n\nRelevant Egyptian law applies, including mandatory consumer and data-protection rules. Contacting support does not prevent recourse to the Consumer Protection Agency, the relevant regulator or the courts. These terms do not require you to waive those rights.'),
      GoLegalSection(id: 'updates', titleAr: '14. الخصوصية وتحديث الشروط', titleEn: '14. Privacy and changes to these terms',
        bodyAr: 'توضح سياسة الخصوصية الخاصة بـ Go Customer بيانات الخدمة وأغراض معالجتها والجهات التي تتلقاها ووسائل ممارسة حقوقك. لا تعد الموافقة على هذه الشروط موافقة عامة على التسويق أو على استخدام بياناتك لأغراض غير محددة.\n\nيظهر تاريخ تحديث هذه الشروط أعلى الصفحة. التعديلات الجوهرية تستلزم إخطارًا مناسبًا وموافقة مستقلة عندما يوجب القانون ذلك، ولا تغيّر بأثر رجعي سعر طلب تم الاتفاق عليه أو حقوقًا نشأت قبله. يلزم اتفاق جديد لتعديل طلب قائم.',
        bodyEn: 'The Go Customer privacy notice explains service data, processing purposes, recipients and how to exercise your rights. Accepting these terms is not blanket consent to marketing or unspecified uses of your data.\n\nThe update date appears above. Material changes require appropriate notice and separate consent when legally required. They do not retroactively change an agreed request price or previously accrued rights. Changing an existing request requires a new agreement.'),
    ],
  );

  static const privacy = GoLegalDocument(
    id: 'privacy', titleAr: 'سياسة الخصوصية', titleEn: 'Privacy policy',
    summaryAr: 'تشرح هذه السياسة كيفية التعامل مع بيانات مستخدمي Go Customer عند تصفح الخدمات وطلب مندوب أو مقدم خدمة واستخدام الحساب والمحفظة والتواصل مع الدعم.',
    summaryEn: 'This notice explains how Go Customer user data is handled when browsing services, requesting a courier or provider, using an account or wallet and contacting support.',
    sections: [
      GoLegalSection(id: 'scope', titleAr: '1. نطاق السياسة والتواصل', titleEn: '1. Scope and contact',
        bodyAr: 'تخص هذه السياسة تطبيق العميل Go Customer. تشير «GO» و«نحن» إلى إدارة المنصة في تعاملها مع بياناتك لتشغيل خدماتها. يمكن توجيه استفسارات الخصوصية وطلبات الحقوق إلى «المساعدة والدعم» داخل التطبيق، مع توضيح أن الطلب يخص بيانات Go Customer.\n\nعند استخدام موقع أو واجهة دفع خارجية، تطبق أيضًا سياسة الجهة المعنية على معالجتها الخاصة للبيانات. لا تعفي الاستعانة بمقدم خدمة GO من التزاماتها عن المعالجة التي تتحكم فيها.',
        bodyEn: 'This notice covers the Go Customer customer app. GO and we refer to platform management when handling your data to operate its services. Send privacy questions and rights requests through Help and support in the app, identifying the request as concerning Go Customer data.\n\nWhen you use an external site or payment interface, that provider’s notice also applies to its own processing. Using a provider does not remove GO’s obligations for processing it controls.'),
      GoLegalSection(id: 'data', titleAr: '2. البيانات المرتبطة بالحساب والطلب', titleEn: '2. Account and request data',
        bodyAr: 'تشمل البيانات التي تقدمها الاسم ورقم الهاتف والبريد الإلكتروني وبيانات الحساب والصورة إن أضفتها، والعناوين المحفوظة وبيانات الموقع ونوع الخدمة ووصفها والصور المرفقة. وفي التوصيل، قد تقدم بيانات المستلم وعنواني الاستلام والتسليم.\n\nيرتبط بالخدمة سجل الطلبات والعروض وقبولها أو رفضها وحالة التنفيذ والمبالغ وحالة المدفوعات وعمليات المحفظة ورسائل الدعم والمحادثات عند تفعيلها. قد تتولد كذلك بيانات تقنية لازمة للاتصال والتشغيل، مثل عنوان الإنترنت ونوع الجهاز أو المتصفح ومعرّفات الجلسة والإشعارات وسجلات الأخطاء. لا يلزم جمع كل نوع في كل استخدام.',
        bodyEn: 'Data you supply includes your name, phone number, email, account information and optional photo, saved addresses, location, service category and description, and attached images. Delivery may also require recipient details and pickup and drop-off addresses.\n\nService records include requests, offers and decisions, fulfilment status, amounts, payment status, wallet transactions, support messages and conversations when enabled. Necessary technical data may also arise, such as IP address, device or browser type, session and notification identifiers and error logs. Not every category is needed for every use.'),
      GoLegalSection(id: 'purposes', titleAr: '3. الأغراض والأساس المسموح للمعالجة', titleEn: '3. Purposes and permitted processing grounds',
        bodyAr: 'تستخدم البيانات لتشغيل الحساب، وتحديد الخدمات القريبة، وإرسال الطلب للشركاء المناسبين، وإدارة عروض الأسعار والتواصل والتنفيذ والمدفوعات والمحفظة، وتقديم الدعم وتسوية الشكاوى، ومنع الاحتيال وحماية الخدمة والوفاء بالالتزامات القانونية.\n\nتستند المعالجة إلى موافقة محددة حين تكون مطلوبة، أو إلى ما يلزم لتقديم الخدمة أو تنفيذ اتفاق أو التزام يسمح به القانون. لا تمنح قراءة السياسة أو الموافقة على الشروط وحدها موافقة على أغراض إضافية غير معلنة أو معالجة تحتاج إلى موافقة مستقلة.',
        bodyEn: 'Data is used to operate accounts, find nearby services, send requests to suitable partners, manage quotations, communication, fulfilment, payments and the wallet, provide support and resolve complaints, prevent fraud, protect the service and meet legal obligations.\n\nProcessing relies on specific consent where required or on what is necessary to provide the service or perform an agreement or obligation permitted by law. Reading this notice or accepting terms alone does not consent to undisclosed additional purposes or processing requiring separate consent.'),
      GoLegalSection(id: 'location', titleAr: '4. الموقع الجغرافي والأذونات', titleEn: '4. Location and permissions',
        bodyAr: 'قد يطلب التطبيق أو المتصفح إذن الموقع الدقيق لاختيار عنوان الخدمة والعثور على الشركاء القريبين وحساب المسافة وعرض مواقع الطلب. وقد تحفظ الإحداثيات مع العنوان أو الطلب الذي ترسله؛ إيقاف إذن الموقع لاحقًا لا يمحو السجلات التي سبق إرسالها.\n\nيمكنك مراجعة الأذونات أو إيقافها من إعدادات جهازك أو متصفحك. قد لا تعمل بعض وظائف الخرائط أو البحث عن شريك دون الموقع اللازم، مع بقاء الوظائف التي لا تحتاجه متاحة. لا تعتبر هذه السياسة إذنًا مفتوحًا لتتبع موقعك خارج أغراض الخدمة.',
        bodyEn: 'The app or browser may request precise-location permission to select a service address, find nearby partners, calculate distance and display request locations. Coordinates may be saved with an address or submitted request; later disabling permission does not erase records already sent.\n\nReview or disable permissions in your device or browser settings. Some map or nearby-provider functions may not work without the required location, while functions not requiring it remain available. This notice is not unrestricted permission to track you outside service purposes.'),
      GoLegalSection(id: 'media', titleAr: '5. الصور والمحادثات وبيانات الغير', titleEn: '5. Images, conversations and other people’s data',
        bodyAr: 'تستخدم الصور التي تختار رفعها لتوضيح الخدمة أو المشكلة أو ملف الحساب بحسب الوظيفة. قد يلزم إذن الكاميرا أو اختيار الصور عند استخدامها. تجنب رفع وجوه أو مستندات أو بيانات حساسة لا يحتاجها الطلب، ولا تقدم بيانات مستلم أو شخص آخر دون حق أو إخباره باستخدامها.\n\nتصل الرسائل والصور المرسلة إلى الطرف الذي تراسله أو تقدم إليه الطلب بحسب الوظيفة، وقد تكون سجلات التواصل ذات صلة بالدعم وتسوية النزاع. لا تفترض أن الدردشة قناة لتبادل أسرار الدفع أو أنها مشفرة من طرف إلى طرف؛ لم تقدم هذه السياسة هذا الضمان.',
        bodyEn: 'Images you choose to upload are used to explain the service or problem or for your profile, depending on the feature. Camera or photo-selection permission may be needed. Avoid unnecessary faces, documents or sensitive information, and do not supply recipient or third-party data without entitlement and informing them of its use.\n\nSent messages and images reach the party you contact or request a service from, as applicable. Communication records may be relevant to support and dispute handling. Do not assume chat is a channel for payment secrets or is end-to-end encrypted; this notice makes no such guarantee.'),
      GoLegalSection(id: 'partners', titleAr: '6. مشاركة البيانات مع الشركاء والدعم', titleEn: '6. Sharing with partners and support',
        bodyAr: 'عند إرسال طلب، تتم مشاركة المعلومات اللازمة لتقييمه وتسعيره أو تنفيذه مع الشريك المختار أو الشركاء الذين يوجّه إليهم الطلب حسب نوع الخدمة. قد يشمل ذلك وصف الطلب والموقع والعنوان ووسائل التواصل اللازمة والصور التي أرفقتها؛ وقد تتم بعض المشاركة قبل قبول العرض حتى يتمكن الشريك من تقييمه.\n\nتتاح المعلومات اللازمة كذلك للعاملين المخولين بالدعم والتشغيل وتسوية المدفوعات أو الشكاوى في حدود عملهم. لا يسمح للشريك باستخدام بيانات العميل للمضايقة أو التسويق المستقل أو أغراض لا تتصل بالطلب دون مسوغ قانوني.',
        bodyEn: 'When you submit a request, information needed to assess, quote for or perform it is shared with the selected partner or partners to whom it is directed, depending on the service. This may include the description, location, address, necessary contact details and attached images. Some sharing may occur before offer acceptance so the partner can evaluate the request.\n\nRelevant information is also available to authorised support, operations and payment or complaint-handling personnel within their duties. Partners are not permitted to use customer data for harassment, independent marketing or unrelated purposes without a lawful basis.'),
      GoLegalSection(id: 'providers', titleAr: '7. الخدمات التقنية والاستضافة', titleEn: '7. Technical services and hosting',
        bodyAr: 'يستعين التطبيق بمقدمي خدمات تقنية بحسب المنصة والوظائف المفعلة، مثل Google Maps للخرائط، وPusher للتحديثات الفورية، وخدمات Firebase للمراسلة أو الإشعارات في النسخ المهيأة لها، ومقدم الدفع Paymob عند استخدام مسارات الدفع المرتبطة به، إضافة إلى خدمات الاستضافة. قد تتلقى هذه الجهات البيانات الفنية وبيانات الخدمة اللازمة لدورها.\n\nقد تشمل هذه الخدمات معالجة خارج مصر بحسب إعدادات مقدم الخدمة. تخضع أي معالجة أو نقل للبيانات إلى الخارج للمتطلبات القانونية والضمانات والتراخيص أو الموافقات اللازمة؛ مجرد قبول هذه السياسة لا يغني عنها. لا نقدم ادعاء بأن جميع البيانات مخزنة داخل مصر.',
        bodyEn: 'Depending on the platform and enabled functions, the app uses technical providers such as Google Maps for maps, Pusher for realtime updates, Firebase for messaging or notifications in configured versions, Paymob for payment flows connected to it, and hosting providers. They may receive technical and service data needed for their role.\n\nThese services may involve processing outside Egypt depending on provider settings. Cross-border processing or transfers remain subject to applicable safeguards and required authorisations or consents; accepting this notice does not replace them. We do not claim that all data is stored in Egypt.'),
      GoLegalSection(id: 'shared-systems', titleAr: '8. الأنظمة المشتركة وحدود استخدام البيانات', titleEn: '8. Shared systems and limits on data use',
        bodyAr: 'تستخدم النسخة الحالية خدمات خلفية مشتركة لإدارة الحسابات والطلبات والدفع؛ استقلال اسم Go Customer لا يعني أن جميع الأنظمة أو سجلات الحساب منفصلة تقنيًا عن الخدمات المرتبطة بها. لا يجوز اعتبار هذا الاشتراك إذنًا باستخدام بياناتك لغرض جديد غير معلن.\n\nتقتصر المشاركة على الأغراض المذكورة والأساس المسموح به، أو استجابة لطلب ملزم قانونًا من جهة مختصة. لا تمنح هذه السياسة إذنًا ببيع بياناتك الشخصية أو إتاحتها لتسويق الغير. قبل حذف حساب تستخدمه عبر أكثر من خدمة، تواصل مع الدعم لمعرفة أثر الحذف على الخدمات المرتبطة.',
        bodyEn: 'The current version uses shared backend services for accounts, requests and payments. Go Customer’s separate name does not mean every system or account record is technically isolated from connected services. Shared infrastructure is not permission to use your data for a new undisclosed purpose.\n\nSharing is limited to the stated purposes and permitted grounds, or a legally binding request from a competent authority. This notice does not authorise sale of your personal data or its disclosure for third-party marketing. Before deleting an account used across services, ask support about effects on connected services.'),
      GoLegalSection(id: 'payment-data', titleAr: '9. بيانات الدفع والمحفظة', titleEn: '9. Payment and wallet data',
        bodyAr: 'تدخل بيانات وسيلة الدفع في واجهة مقدم الدفع المختار بحسب المسار المفعّل. ترتبط لدى المنصة بيانات تشغيلية مثل المبلغ ورقم العملية وحالتها والرصيد والشحن والتحويل والاسترداد، وقد يلزم رقم الهاتف المرتبط بالمحفظة أو بيانات فوترة بحسب الوسيلة.\n\nلا ترسل رقم البطاقة الكامل أو رمز الأمان أو الرقم السري أو رمز الاستخدام الواحد عبر وصف الطلب أو الصور أو الدردشة أو الدعم. يحدد مقدم الدفع في سياسته معالجته للبيانات التي تدخلها لديه؛ لا نعد هنا بإجراءات تخزين أو شهادات أمان لم يتم التحقق منها.',
        bodyEn: 'Payment-method information is entered through the selected payment provider’s interface according to the enabled flow. The platform holds operational records such as amounts, transaction references and status, balance, top-ups, transfers and refunds. A wallet-linked phone number or billing details may be needed for the selected method.\n\nDo not send full card numbers, security codes, PINs or one-time codes through descriptions, images, chat or support. The payment provider’s notice explains its handling of information entered there. No unverified storage practice or security certification is promised here.'),
      GoLegalSection(id: 'storage', titleAr: '10. التخزين المحلي وتسجيل الدخول الخارجي', titleEn: '10. Local storage and external sign-in',
        bodyAr: 'يحفظ التطبيق أو نسخة الويب بيانات تشغيل على جهازك، مثل رمز الجلسة واللغة ومعرّف الحساب والعنوان أو الموقع المختار وبعض تفضيلات العرض. تساعد هذه البيانات على استمرار الدخول وعرض الخدمة، ويمكن إزالة بيانات الموقع من إعدادات المتصفح أو التطبيق؛ قد يؤدي ذلك إلى تسجيل الخروج وفقد التفضيلات المحلية.\n\nإذا اخترت تسجيل الدخول بواسطة حساب خارجي وكانت الميزة مفعّلة، يعالج مقدم الهوية بيانات الدخول وفق سياسته ويزوّد GO بالبيانات اللازمة للربط. قد تستخدم خدماته ملفات تعريف ارتباط أو تخزينًا خاصًا بها. حذف التخزين المحلي لا يحذف بيانات الحساب الموجودة على الخادم.',
        bodyEn: 'The app or web version stores operational data on your device, such as a session token, language, account identifier, selected address or location and display preferences. This supports sign-in and service display. Clearing site or app data may sign you out and remove local preferences.\n\nIf you choose an enabled external sign-in option, the identity provider processes sign-in under its own policy and supplies GO with information needed to link the account. Its services may use cookies or their own storage. Clearing local storage does not delete server-side account records.'),
      GoLegalSection(id: 'messages', titleAr: '11. الإشعارات والتسويق', titleEn: '11. Notifications and marketing',
        bodyAr: 'قد تتلقى رسائل تشغيل مرتبطة بالدخول أو الطلب أو عرض السعر أو الدفع أو الدعم بحسب الوسيلة المفعلة. يمكنك إدارة إذن الإشعارات من الجهاز أو المتصفح، مع العلم أن إيقافه قد يمنع ظهور تنبيهات مهمة.\n\nالرسائل التسويقية الإلكترونية تحتاج إلى الموافقة المطلوبة قانونًا وإتاحة وسيلة واضحة لرفضها أو سحبها، ولا يعتبر قبول شروط الخدمة وحده موافقة تسويقية. يمكنك مخاطبة الدعم لطلب إيقاف التسويق، ولا يوقف ذلك الرسائل الضرورية لتنفيذ التزام قائم أو حماية الحساب.',
        bodyEn: 'You may receive operational messages about sign-in, requests, quotations, payments or support through enabled channels. Manage notification permission through your device or browser; disabling it may hide important alerts.\n\nElectronic marketing requires legally required consent and a clear way to refuse or withdraw it. Accepting service terms alone is not marketing consent. Contact support to request marketing cessation; this does not stop messages necessary for an existing obligation or account protection.'),
      GoLegalSection(id: 'retention', titleAr: '12. الاحتفاظ بالبيانات', titleEn: '12. Retention',
        bodyAr: 'يرتبط الاحتفاظ بنوع البيانات والغرض منها: تشغيل الحساب والطلبات القائمة، وتسوية المدفوعات والرصيد، ومعالجة الشكاوى، ومنع الاحتيال، وتنفيذ التزامات الحفظ القانونية. لا توجد في هذه السياسة مدة واحدة لجميع البيانات، ولا يصح الاحتفاظ ببيانات دون غرض مشروع مستمر.\n\nعند انتهاء الغرض، يكون الأصل حذف البيانات أو جعلها غير قابلة لربطها بشخص، مع مراعاة السجلات التي يجب الاحتفاظ بها قانونًا والنسخ الاحتياطية اللازمة لدورة الحفظ. يمكن سؤال الدعم عن المدة أو المعيار المطبق على بياناتك، ولا يبرر الاحتفاظ المحدود استخدامها لتسويق جديد.',
        bodyEn: 'Retention depends on data type and purpose: operating accounts and active requests, settling payments and balances, handling complaints, preventing fraud and meeting legal recordkeeping obligations. There is no single period for all data, and data should not be kept without a continuing legitimate purpose.\n\nWhen the purpose ends, data should be deleted or made non-identifiable, subject to legally required records and backups within the retention cycle. Ask support about the applicable period or criterion. Limited retention does not justify new marketing use.'),
      GoLegalSection(id: 'rights', titleAr: '13. حقوقك وحذف الحساب', titleEn: '13. Your rights and account deletion',
        bodyAr: 'يمكنك طلب معرفة بياناتك والوصول إليها أو الحصول على نسخة منها، وتصحيحها أو تحديثها، وطلب حذفها أو تقييد معالجتها أو الاعتراض عليها، وسحب موافقة سابقة بحسب ما يسمح به القانون. سحب الموافقة لا يمحو مشروعية معالجة سابقة ولا يلغي التزام حفظ مستقل يوجبه القانون.\n\nاستخدم إعدادات الحساب للتعديلات المتاحة، أو «حذف الحساب» حيث يظهر، أو أرسل طلبًا واضحًا عبر «المساعدة والدعم». قد يلزم تحقق مناسب من هويتك دون طلب كلمة مرورك أو رمز الدفع. إزالة التطبيق وحدها لا تحذف الحساب، وقد يستلزم حذف حساب مرتبط مراجعة أثره على خدمات أخرى وتسوية الالتزامات مع الاحتفاظ فقط بما يلزم قانونًا. يمكنك الشكوى إلى الجهة المختصة بحماية البيانات أو القضاء دون أن يمنعك التواصل مع الدعم.',
        bodyEn: 'You may request information about and access to your data or a copy, correction or updates, deletion, restriction or objection, and withdrawal of prior consent as permitted by law. Withdrawal does not invalidate earlier lawful processing or remove a separate legal retention obligation.\n\nUse available account settings, Delete account where shown, or send a clear request through Help and support. Appropriate identity verification may be needed, but not your password or payment code. Uninstalling alone does not delete an account. Deleting a linked account may require checking effects on other services and settling obligations while retaining only legally necessary records. You may complain to the competent data-protection authority or the courts; contacting support does not prevent this.'),
      GoLegalSection(id: 'security', titleAr: '14. الأمان وبيانات القُصّر', titleEn: '14. Security and children’s data',
        bodyAr: 'يتطلب تشغيل الخدمة اتخاذ تدابير تقنية وتنظيمية مناسبة لحماية البيانات وقصر الوصول عليها بحسب الحاجة. لا يوجد ضمان مطلق يمنع كل اختراق، ولا تقدم هذه السياسة ادعاء بمستوى تشفير أو اعتماد لم يتم إثباته. عند وقوع خرق يخضع للإبلاغ، تطبق التزامات الإخطار والإجراءات المقررة قانونًا.\n\nالتطبيق غير موجّه للأطفال لإنشاء حسابات أو التعاقد مستقلين. لا ترفق بيانات قاصر أو صوره إلا عند الضرورة وبالمسوغ والموافقة اللازمة من ممثله القانوني. يمكن لولي الأمر التواصل مع الدعم بشأن بيانات قاصر قدمت دون تفويض.',
        bodyEn: 'Operating the service requires appropriate technical and organisational safeguards and need-based access. No absolute guarantee prevents every breach, and this notice does not claim an unproven encryption level or certification. Legally required notifications and procedures apply to reportable breaches.\n\nThe app is not directed at children for independent account creation or contracting. Do not attach a minor’s details or images except where necessary and with the required lawful basis and legal representative’s consent. A guardian may contact support about a minor’s data submitted without authority.'),
      GoLegalSection(id: 'updates', titleAr: '15. تحديث السياسة', titleEn: '15. Notice updates',
        bodyAr: 'تظهر نسخة السياسة وتاريخ تحديثها أعلى الصفحة. يجب توضيح أي تغيير جوهري في أنواع البيانات أو أغراض المعالجة أو جهات المشاركة وإخطارك به بالطريقة المناسبة، والحصول على موافقة جديدة عندما يتطلب القانون ذلك. نشر نص معدل لا ينشئ وحده موافقة على غرض جديد.\n\nللسؤال عن السياسة أو الجهة المسؤولة عن بياناتك أو لتقديم طلب، استخدم زر «المساعدة والدعم» في هذه الصفحة.',
        bodyEn: 'The notice version and update date appear above. Material changes to data categories, purposes or recipients must be explained and appropriately notified, with fresh consent when legally required. Publishing revised text alone does not create consent to a new purpose.\n\nFor questions about this notice, the party responsible for your data or a rights request, use Help and support on this page.'),
    ],
  );
}
